### ISSUE TITLE
Is it possible to add import zip file from netex zip file?

### ISSUE THREAD

**Issue by reidsneo** [ciaranmccormick/transidate#12]
Is it possible to add the import feature for netex zip file?
https://data.ndovloket.nl/netex/cxx/

**Comment by ciaranmccormick** [comment]
How about being able to configure the schemas using an `.ini` file?
The idea would be you could add the schemas zip `url` and the `root` XML file to the configuration and then pass the file to `transidate`.

```ini
# myschemas.ini
[CUSTOM]
url=http://someshcema.z
root=NeTEx_publication.xsd
```

```sh
transidate --version CUSTOM --schemas myschemas.ini netexfile.xml
```

**Comment by reidsneo** [comment]
yes that would be great if we are able to use different profile dynamically

**Comment by reidsneo** [comment]
I just tried the custom schema support, using netex cen eu schema publication 1.10 
https://github.com/NeTEx-CEN/NeTEx
and data from ndov loket
https://data.ndovloket.nl/netex/cxx/
it's take very long time to process, and after that this message is show up

![image](https://user-images.githubusercontent.com/12298979/111961540-26296100-8b2c-11eb-93ee-b937ed68ef77.png)

**Comment by ciaranmccormick** [comment]
From the error, this looks like an issue with  [lxml](https://github.com/lxml/lxml). Are you able to test with a smaller file, I think the error you're seeing could be related to the file size?
Big files can take a long time to validate with `lxml`, on a standard laptop I've seen 100MB files take 45 minutes to validate.

**Comment by reidsneo** [comment]
For smaller file is good to go, unfortunately currently I working with the data from NL profile which they provide huge amount for data source.
but the main issue for the custom validation profile is supported it's a great news thanks!
Feel free to close the issue
